# --- settings for validation workflow using externally specified model  --- #
output-dir: "validation-msprime-output"  # where to place validation results and simulations
random-seed: 1024  # global random seed
num-replicates: 5  # number of replicate ARGs to simulate
mask-sequence: [0.0, 0]  # randomly mask intervals with this [density, mean length]
mask-variants: 0.2  # randomly mask this proportion of variants
inaccessible-bed: "example/example.mask.bed"  # path to bedfile with masked intervals (will be combined with simulated intervals, can be omitted)
prop-mispolarise: 0.0  # randomly mispolarise this proportion of biallelic variants (or "maf" for major-allele polarisation)
time-grid: [1, 7, 50]  # [log10 start, log10 stop, number of intervals] for mutation age plot
project-afs-to: 2  # project AFS to this number of haploids per population for mutation age plot
singer-snakemake-config: "config/example_config.yaml"  # path to singer-snakemake config to use (mutation/recombination rates ignored)
singer-snakemake-config-override:  # key-values to override in config file
    polarised: True
msprime-config:  # simulation settings
    demographic-model: "example/example.demes.yaml"  # path to demes-formatted model
    samples: {"pop_0": 10, "pop_1": 10, "pop_2": 10}  # sampled individuals per population
    recombination-map: "example/example.hapmap"  # path to hapmap-format recombination map
    mutation-rate: 1.0e-8  # per base mutation rate
